### ISSUE TITLE
Json Null error

### ISSUE THREAD

**Issue by TerZer** [InventivetalentDev/CustomBlocks#1]
I have this error:
`[22:35:56 INFO]: TerZer issued server command: /customblockcreate Ore https://i.
imgur.com/BvIo4DW.png
[22:36:06 INFO]: JsonNull
[22:36:06 WARN]: Exception in thread "pool-11-thread-1"
[22:36:06 WARN]: java.lang.RuntimeException: java.lang.UnsupportedOperationExcep
tion: JsonNull
[22:36:06 WARN]:        at org.inventivetalent.skullclient.SkullClient$1.run(Sku
llClient.java:87)
[22:36:06 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[22:36:06 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[22:36:06 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:36:06 WARN]: Caused by: java.lang.UnsupportedOperationException: JsonNull
[22:36:06 WARN]:        at com.google.gson.JsonElement.getAsInt(JsonElement.java
:243)
[22:36:06 WARN]:        at org.inventivetalent.skullclient.SkullClient$1.run(Sku
llClient.java:79)
[22:36:06 WARN]:        ... 3 more
[22:36:10 INFO]: JsonNull
[22:36:10 WARN]: Exception in thread "pool-11-thread-2"
[22:36:10 WARN]: java.lang.RuntimeException: java.lang.UnsupportedOperationExcep
tion: JsonNull
[22:36:10 WARN]:        at org.inventivetalent.skullclient.SkullClient$1.run(Sku
llClient.java:87)
[22:36:10 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[22:36:10 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[22:36:10 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:36:10 WARN]: Caused by: java.lang.UnsupportedOperationException: JsonNull
[22:36:10 WARN]:        at com.google.gson.JsonElement.getAsInt(JsonElement.java
:243)
[22:36:10 WARN]:        at org.inventivetalent.skullclient.SkullClient$1.run(Sku
llClient.java:79)
[22:36:10 WARN]:        ... 3 more
[22:36:14 INFO]: JsonNull
[22:36:14 WARN]: Exception in thread "pool-11-thread-3"
[22:36:14 WARN]: java.lang.RuntimeException: java.lang.UnsupportedOperationExcep
tion: JsonNull
[22:36:14 WARN]:        at org.inventivetalent.skullclient.SkullClient$1.run(Sku
llClient.java:87)
[22:36:14 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[22:36:14 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[22:36:14 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:36:14 WARN]: Caused by: java.lang.UnsupportedOperationException: JsonNull
[22:36:14 WARN]:        at com.google.gson.JsonElement.getAsInt(JsonElement.java
:243)
[22:36:14 WARN]:        at org.inventivetalent.skullclient.SkullClient$1.run(Sku
llClient.java:79)
[22:36:14 WARN]:        ... 3 more`

So I tried to find where is this problem.
1. Checked if image is still there: https://i.imgur.com/BvIo4DW.png
2. Checked if image is 32x64 or 64x64
3. Went digging code and found out where it might got this problem.
4. Found out that code runs this: https://skulls.inventivetalent.org/api/?url=%shttps://i.imgur.com/BvIo4DW.png and that's where it got that null I guess..

Version used: 1.12.2
Image: https://i.imgur.com/BvIo4DW.png

**Comment by InventivetalentDev** [comment]
Ah, right. Looks like I never updated this plugin to use MineSkin. Will do asap c:

**Comment by SuperOP535** [comment]
The 4. has an %s prefix which seems to break the link, I removed the %s and the page worked fine

**Comment by SuperOP535** [comment]
And also your link in the command has a space between i. and imgur

**Comment by lebronjames4** [comment]
@InventivetalentDev Removing the %s still comes up with null for me
